cards/config/routes.rb
Cards::Application.routes.draw do
  root to: "main#index"

  resources :decks do
    resources :cards
  end

  get "main/rules", :to => "main#rules"

  get "games/new", :to => "games#new"
  post "games/play", :to => "games#play"
  get "games/buy", :to => "games#buy"
  get "games/game_end", :to => "games#game_end"
  get "games/event", :to => "games#event"
  get "games/cargo", :to => "games#cargo"
  get "games/jettison", :to => "games#jettison"
  get "games/station", :to => "games#station"
  get "games/sell", :to => "games#sell"
  get "games/process_round", :to => "games#process_round"
  get "games/shield_up", :to => "games#shield_up"
  get "games/trim", :to => "games#trim"

end

cards/app/models/game.rb
class Game < ActiveRecord::Base
end

cards/app/controllers/games_controller.rb
 class GamesController < ApplicationController

# -------------------- System Related -----------------
  def new
    session[:ship] = Ship.new
    @event_results = User.new
    initialize_player(session[:ship].attributes)
    initialize_system
    round_housekeeping
    redirect_to games_process_round_path
  end


  def play
    round_housekeeping
    @player.speed = params[:speed].to_i
    redirect_to games_process_round_path
  end


  def game_end
  end

# -------------------- Round Upkeep -----------------
  def process_round
    @event_results = User.new
    game_over?
    if session[:game_status] != "continue"
      redirect_to games_game_end_path and return
    else
      render "play"
    end
  end

# -------------------- Space Events -----------------
  def event
    @event_results = User.new
    @event_card = Card.find(params[:card])
    compute_attack if @event_card.card_type == "enemy" || @event_card.card_type == "boss"

    respond_to do |format|
      format.js
    end
  end


  def shield_up
    card = Card.find(params[:card])
    if @player.energy >= 1 && card.effect == "shield"
      charge_amount = card.modifier.to_i
      until charge_amount <= 0 || @player.shield >= session[:ship].max_shield do
         @player.energy -= 1
         charge_amount -= 1
         @player.shield += 1
      end
      flash[:notice] = "Shield capacitor now at #{@player.shield} units"
      session[:player_discard].push(card)
      session[:player_hand].delete(card)
    else
      flash[:notice] = "Not enough energy to charge shields"
    end

    respond_to do |format|
      format.js
    end
  end


  def cargo
    @event_results = User.new
    @cargo_card = Card.find(params[:card])
    if enemy_present?
      flash[:notice] = "Cannot safely loot cargo while enemies are present"
    else
      loot_cargo if @cargo_card.effect == "cargo"
    end

    respond_to do |format|
      format.js
    end
  end

  def jettison
    @cargo_card = Card.find(params[:card])
    @player.cargo -= @cargo_card.modifier.to_i
    flash[:notice] = "#{@cargo_card.flavor_text} was jettisoned"
    @player.cargo_bay.delete(@cargo_card)

    respond_to do |format|
      format.js
    end
  end

# -------------------- Station Activities -----------------
  def station
    if enemy_present? && session[:location] == "space"
      flash[:notice] = "Cannot dock at stations while enemy is present"
      redirect_to games_process_round_path
    else
      refresh_buy_deck if session[:location] == "space"
      @player.round += 1 if session[:location] == "space"
      session[:location] = "station"
      if params[:service] == "repair"
        repair_ship
      elsif params[:service] == "hire"
        hire_crew
      elsif params[:service] == "recharge"
        recharge_energy
      elsif params[:service] == "shield"
        recharge_shield
      elsif params[:service] == "malfunction"
        remove_malfunction_card
      elsif params[:service] == "tuning"
        session[:tuned] = "in_progress"
      else
        flash[:notice] = "Docked at outpost."
      end
    end
  end


  def buy
    @event_results = User.new
    @buy_card = Card.find(params[:card])
    if @buy_card.cost.to_i > @player.credit
      flash[:notice] = "not enough cash. buy cancelled"
    else
      @player.credit -= @buy_card.cost.to_i
      flash[:notice] = "bought card"
      if @buy_card.card_type != "ship_upgrade"
        session[:player_discard].push(session[:buy_hand].delete(Card.find(params[:card])))
      elsif @buy_card.card_type == "ship_upgrade"
        install_upgrade
        session[:buy_hand].delete(Card.find(params[:card]))
      end
    end

    respond_to do |format|
      format.js
    end
  end


  def sell
    @cargo_card = Card.find(params[:card])
    @player.credit += @cargo_card.cost.to_i
    @player.cargo -= @cargo_card.modifier.to_i
    flash[:notice] = "Sold #{@cargo_card.flavor_text} for #{@cargo_card.cost} credits."
    @player.cargo_bay.delete(@cargo_card)

    respond_to do |format|
      format.js
    end
  end

  def trim
    if @player.credit >= 1000
      @player.credit -= 1000
      session[:player_discard].delete(Card.find(params[:card]))
      session[:tuned] = "completed"
    else
      flash[:notice] = "Not enough money for service"
    end

    respond_to do |format|
      format.js
    end
  end



end

cards/app/views/games/_game.html.erb
<fieldset class="event_area">
  <legend>Game Events</legend>
  <% session[:event_hand].each do |card| %>
    <div class="card">
      <div class="card_type"><%= card.card_type %></div><br>
      <div class="card_effect"><%= card.effect %></div><br>
      <div class="card_modifier"><%= card.modifier %></div><br>
      <div class="card_flavor_text">"<%= card.flavor_text %>"</div><br>
    </div>
  <% end %>
</fieldset>


<fieldset class="buy_area">
  <legend>Buy Area</legend>
  <% session[:buy_hand].each do |card| %>
    <div class="card">
      <div class="card_type"><%= card.card_type %></div>
      <div class="card_effect"><%= card.effect %></div>
      <div class="card_modifier"><%= card.modifier %></div><br>
      <div class="card_flavor_text">"<%= card.flavor_text %>"</div><br>
      <div class="card_cost">Cost: <%= card.cost %></div>
    </div>
  <% end %>
</fieldset><br>


<fieldset class="game_area">
  <legend>Player Hand</legend>
  <div class="player_hand">
    <% session[:player_hand].each do |card| %>
      <div class="card">
        <div class="card_type"><%= card.card_type %></div><br>
        <div class="card_effect"><%= card.effect %></div><br>
        <div class="card_modifier"><%= card.modifier %></div><br>
        <div class="card_flavor_text">"<%= card.flavor_text %>"</div><br>
      </div>
    <% end %>
  </div><br>

  <div class="round_details">
    <% tally_resources %>
    <table>
      <tr>
        <th>Draw pile: <%= session[:player_deck].size %></th>
        <th>Discard: <%= session[:player_discard].size %></th>
        <th>Attack: <%= @round_stats.attack %></th>
        <th>Shield: <%= @round_stats.shield %></th>
        <th>Energy: <%= @round_stats.energy %></th>
        <th>Credit: <%= @round_stats.credit %></th>
      </tr>
    </table>
  </div><br>

  <div class="resource_hud">
    <table>
      <tr>
        <th>Hull Strength: <%= session[:hull] %></th>
        <th>Shield Strength: <%= session[:shield] %></th>
        <th>Energy Reserves: <%= session[:energy] %></th>
        <th>Credit: <%= session[:credit] %></th>
      </tr>
    </table>
  </div>
</fieldset><br>

<% if check_game_over? %>
  <%= link_to "Game over", root_path %>
<% else %>
  <%= link_to "Play hand", games_play_path, method: :post %>
<% end %>

cards/app/views/games/buy.js.erb
console.log("updating partials")
$('.buy_area').replaceWith('<%= escape_javascript(render(:partial => 'shared/buy_deck' )) %>' )
$('.resource_hud').replaceWith('<%= escape_javascript(render(:partial => 'shared/resource_hud')) %>' )
$('.debug').replaceWith('<%= escape_javascript(render(:partial => 'shared/dev_debug', :locals => { :notes => "none"})) %>' )
$('.system_message').replaceWith('<%= escape_javascript(render(:partial => 'shared/system_message')) %>')
  bindStationEvent();

cards/app/views/games/cargo.js.erb
console.log("Checking cargo space")
$('.event_area').replaceWith('<%= escape_javascript(render(:partial => 'shared/event_deck')) %>')
$('.resource_hud').replaceWith('<%= escape_javascript(render(:partial => 'shared/resource_hud')) %>' )
$('.system_message').replaceWith('<%= escape_javascript(render(:partial => 'shared/system_message')) %>')
$('.cargo_area').replaceWith('<%= escape_javascript(render(:partial => 'shared/cargo_bay')) %>')
bindEvent();

cards/app/views/games/event.js.erb
console.log("Checking attack")
$('.event_area').replaceWith('<%= escape_javascript(render(:partial => 'shared/event_deck')) %>')
$('.resource_hud').replaceWith('<%= escape_javascript(render(:partial => 'shared/resource_hud')) %>' )
$('.system_message').replaceWith('<%= escape_javascript(render(:partial => 'shared/system_message')) %>')
bindEvent();

cards/app/views/games/game_end.html.erb
<% if session[:game_status] == "lost" %>
  you lose<br>
<% elsif session[:game_status] == "win" %>
  You win!<br>
<% end %>

<%= link_to "Home", root_path %>

cards/app/views/games/jettison.js.erb
console.log("Out the hatch it goes")
$('.cargo_area').replaceWith('<%= escape_javascript(render(:partial => 'cargo_bay')) %>')
$('.system_message').replaceWith('<%= escape_javascript(render(:partial => 'system_message')) %>')
bindEvent();

cards/app/views/games/play.html.erb
<%= form_tag(games_play_path) do %>
  <%= render "shared/resource_hud" %>
  <%= render "shared/system_message" %>
  <%= render "shared/event_deck" %>
  <%= render "shared/player_area" %>
  <%= render "shared/cargo_bay" %>

<% end %>
  <%= link_to "Station", games_station_path, :class => "link_button" %>
  <%= link_to "Home", root_path, class: "link_button", data: { confirm: "Quit game?" }%>

<%#= render "shared/dev_debug" %>
Deck size: <%= session[:player_deck].size %> /
Discards: <%= session[:player_discard].size %>

cards/app/views/games/sell.js.erb
console.log("selling cargo")
$('.cargo_area').replaceWith('<%= escape_javascript(render(:partial => 'shared/cargo_bay')) %>')
$('.resource_hud').replaceWith('<%= escape_javascript(render(:partial => 'shared/resource_hud')) %>')
$('.system_message').replaceWith('<%= escape_javascript(render(:partial => 'shared/system_message')) %>')
bindStationEvent();

cards/app/views/games/shield_up.js.erb
console.log("Shield capacitor charged")
$('.player_area').replaceWith('<%= escape_javascript(render(:partial => 'shared/player_area')) %>')
$('.resource_hud').replaceWith('<%= escape_javascript(render(:partial => 'shared/resource_hud')) %>')
$('.system_message').replaceWith('<%= escape_javascript(render(:partial => 'shared/system_message')) %>')
bindEvent();

cards/app/views/games/station.html.erb
<%= render "shared/resource_hud" %>
<%= render "shared/system_message" %>
<%= render "shared/buy_deck" %>
<%= render "shared/station_services" %>
<%= render "shared/tuning" if session[:tuned] == "in_progress" %>
<%= render "shared/cargo_bay" %>

<%= link_to "Home", root_path, class: "link_button", data: { confirm: "Quit game?" }%>
Current turn: <%= @player.round %> / <%= session[:game_round_limit] %>

cards/app/views/games/trim.js.erb
console.log("Tuning ship systems")
$('.resource_hud').replaceWith('<%= escape_javascript(render(:partial => 'shared/resource_hud')) %>')
$('.system_message').replaceWith('<%= escape_javascript(render(:partial => 'shared/system_message')) %>')
$('.station_services').replaceWith('<%= escape_javascript(render(:partial => 'shared/station_services')) %>')
$('.mechanic_area').remove();
bindStationEvent();