cards/config/routes.rb
Cards::Application.routes.draw do
  root to: "main#index"

  resources :decks do
    resources :cards
  end

  get "main/rules", :to => "main#rules"

  get "games/new", :to => "games#new"
  post "games/play", :to => "games#play"
  get "games/buy", :to => "games#buy"
  get "games/game_end", :to => "games#game_end"
  get "games/event", :to => "games#event"
  get "games/cargo", :to => "games#cargo"
  get "games/jettison", :to => "games#jettison"
  get "games/station", :to => "games#station"
  get "games/sell", :to => "games#sell"
  get "games/process_round", :to => "games#process_round"
  get "games/shield_up", :to => "games#shield_up"
  get "games/trim", :to => "games#trim"

end

cards/app/models/deck.rb
class Deck < ActiveRecord::Base
  attr_accessible :name, :deck_type
  has_many :cards, dependent: :destroy

  validates :name, presence: true
  validates :deck_type, presence: true
end

cards/app/controllers/decks_controller.rb
class DecksController < ApplicationController

  def index
    @decks = Deck.all
  end

  def new
    @deck = Deck.new
  end

  def create
    @deck = Deck.new(params[:deck])
    if @deck.save
      redirect_to action: "index"
    else
      render 'new'
    end
  end

  def show
    @deck = Deck.find(params[:id])
  end

  def edit
    @deck = Deck.find(params[:id])
  end

  def update
    @deck = Deck.find(params[:id])
    if @deck.update_attributes(params[:deck])
      redirect_to @deck
    else
      render "edit"
    end
  end

  def show
    @deck = Deck.find(params[:id])
  end

  def destroy
    @deck = Deck.find(params[:id])
    @deck.destroy
    redirect_to decks_path
  end

end

cards/app/views/decks/_deck.html.erb
<%= form_for @deck do |deck| %>
  <% if @deck.errors.any? %>
    <div class="alert">
      <%= pluralize(@deck.errors.count, "error") %> Deck not saved.
      <ul>
        <% @deck.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %><br>

  <table>
    <tr>
      <th>
      <%= deck.label :"Deck Name" %>
      </th>
      <td>
        <%= deck.text_field :name %>
      </td>
    </tr>
    <tr>
      <th>
        <%= deck.label :"Deck Type" %>
      </th>
      <td>
        <%= deck.text_field :deck_type %>
      </td>
    </tr>
    <tr>
      <th>
      </th>
      <td>
        <%= deck.submit "Save" %><br>
      </td>
    </tr>
  </table>
<% end %>

cards/app/views/decks/_new_deck.html.erb
<%= form_for @deck do |deck| %>
  <% if @deck.errors.any? %>
    <div class="alert">
      <%= pluralize(@deck.errors.count, "error") %> Deck not saved.
      <ul>
        <% @deck.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %><br>

  <table>
    <tr>
      <th>
      <%= deck.label :"Deck Name" %>
      </th>
      <td>
        <%= deck.text_field :name %>
      </td>
    </tr>
    <tr>
      <th>
        <%= deck.label :"Deck Type" %>
      </th>
      <td>
        <%= deck.text_field :deck_type %>
      </td>
    </tr>
    <tr>
      <th>
      </th>
      <td>
        <%= deck.submit "Save" %><br>
      </td>
    </tr>
  </table>
<% end %>

cards/app/views/decks/edit.html.erb
<div class="heading">Deck edit page</div>

<%= render "deck" %>

<%= link_to "Home", root_path %>

cards/app/views/decks/index.html.erb
<p><div class="heading">Deck list page</div></p>

<table>
  <tr>
    <th>Name</th>
    <th>Type</th>
  </tr>

  <% @decks.each do |deck| %>
  <tr>
    <td><%= deck.name %></td>
    <td><%= deck.deck_type %></td>
    <td><%= link_to "Show", deck_path(deck) %></td>
    <td><%= link_to "Edit", edit_deck_path(deck) %></td>
    <td><%= link_to "Delete", deck_path(deck), method: :delete, data: { confirm: "Confirm deletion?" } %></td>

  </tr>
  <% end %>
</table>

<br>
<%= link_to "Home", root_path %>

cards/app/views/decks/new.html.erb
<p><div class="heading">Create new deck</div></p>

<div class="new_form">
  <%= render "deck" %><br>
</div>
<br>
<%= link_to "Home", root_path %>

cards/app/views/decks/show.html.erb
<div class="heading">Deck details</div><br>

Name: <%= @deck.name %><br>
Type: <%= @deck.deck_type %><br>

<br>
Cards: <%= link_to "Create", new_deck_card_path(@deck)%>

<div class="card_list">
  <% cards = @deck.cards.order(:card_type).order(:effect).order(:modifier) %>
  <table>
    <tr>
      <th>ID</th>
      <th>Card Type</th>
      <th>Effect</th>
      <th>Modifiers</th>
      <th>Flavor Text</th>
      <th>Action</th>
    </tr>
    <% cards.each do |card| %>
      <tr>
        <td><%= card.id %></td>
        <td><%= link_to card.card_type, edit_deck_card_path(@deck.id, card) %></td>
        <td><%= card.effect %></td>
        <td><%= card.modifier %></td>
        <td><%= card.flavor_text %></td>
        <td><%= link_to "Delete", deck_card_path(@deck, card), method: :delete, data: { confirm: "Confirm card deletion?" } %></td>
      </tr>
    <% end %>
  </table>
</div>

<br><%= link_to "Home", root_path %>